<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><AssemblyVersion>0.1.1.0</AssemblyVersion><RootNamespace>Jellyfin.Plugin.KidGuard</RootNamespace></PropertyGroup><ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App"/><PackageReference Include="Jellyfin.Controller" Version="12.0.0" ExcludeAssets="runtime"/><PackageReference Include="Jellyfin.Model" Version="12.0.0" ExcludeAssets="runtime"/><ProjectReference Include="../KidGuard.Core/KidGuard.Core.csproj"/><EmbeddedResource Include="UI/*"/></ItemGroup></Project>
