export default function (view) {
        'use strict';
        var root = view.querySelector('#kidguardRoot'), dashboard, profile, rows = [], selected = new Set(), page = 0, poll, mode = 'home', busy = false;
        var dimensions = ['Violence','Fear','SexualContent','Nudity','Profanity','Substances','MatureThemes','DeathGrief','DisturbingImagery'];
        function esc(v) { return String(v == null ? '' : v).replace(/[&<>"']/g, function(c) { return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]; }); }
        function api(path, data) { var args = {type: data === undefined ? 'GET' : 'POST', url: ApiClient.getUrl('KidGuard/' + path), dataType:data === undefined || path === 'Profiles' ? 'json' : undefined}; if (data !== undefined) { args.data = JSON.stringify(data); args.contentType = 'application/json'; } return ApiClient.ajax(args); }
        function button(action, text, primary) { return '<button type="button" class="emby-button raised '+(primary?'button-submit':'')+'" data-act="'+action+'">'+esc(text)+'</button>'; }
        function option(value, text, chosen) { return '<option value="'+esc(value)+'" '+(value === chosen?'selected':'')+'>'+esc(text)+'</option>'; }
        function field(name, label, value, type, extra) { return '<label class="kg-field">'+esc(label)+'<input class="emby-input" name="'+name+'" type="'+(type||'text')+'" value="'+esc(value)+'" '+(extra||'')+'></label>'; }
        function checked(name, label, value) { return '<label class="kg-check"><input type="checkbox" name="'+name+'" '+(value?'checked':'')+'>'+esc(label)+'</label>'; }
        function select(name, label, values, current) { return '<label class="kg-field">'+esc(label)+'<select class="emby-select" name="'+name+'">'+values.map(function(v){return option(v[0],v[1],current);}).join('')+'</select></label>'; }
        function shell(content) {
            root.innerHTML = '<style>.kg{max-width:1200px;margin:auto;padding:20px 12px}.kg h1{font-size:32px;margin:0}.kg h2{margin-top:0}.kg p{line-height:1.6}.kg-muted{opacity:.7}.kg-bar,.kg-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:16px 0}.kg-bar{justify-content:space-between}.kg-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(235px,1fr));gap:16px}.kg-card{background:rgba(128,128,128,.09);border:1px solid rgba(128,128,128,.22);border-radius:14px;padding:22px}.kg-field{display:flex;flex-direction:column;gap:9px;margin:10px 0}.kg-field input,.kg-field select{width:auto;min-width:80px}.kg-check{display:flex;align-items:center;gap:8px;padding:8px 0}.kg small{font-size:12px}.kg table{width:100%;border-collapse:collapse}.kg td,.kg th{text-align:left;padding:13px 10px;border-bottom:1px solid #7774}.kg .kg-table{overflow:auto}.kg .kg-status{font-weight:bold}.kg .Allow{color:#6cdbb2}.kg .Block{color:#ff9eae}.kg .Review{color:#f3ce79}.kg .kg-stat{font-size:28px;font-weight:bold}.kg .kg-notice{border-left:3px solid #00a4dc;padding:12px 16px;background:#00a4dc12}.kg .kg-link{background:none;color:inherit;border:0;text-align:left;cursor:pointer;text-decoration:underline;font:inherit}.kg .kg-inline{display:inline-flex;gap:6px}.kg .kg-danger{border-left-color:#ff9eae}.kg .kg-progress{width:100%;height:8px}.kg details{margin:15px 0}.kg summary{cursor:pointer;padding:10px 0}.kg button{cursor:pointer}.kg input[type=checkbox]{width:18px;height:18px}.kg .kg-top{letter-spacing:.15em;text-transform:uppercase;font-size:11px;color:#6cc7ef}.kg pre{white-space:pre-wrap}</style><div class="kg"><div class="kg-bar"><div><div class="kg-top">Your family · Your choices</div><h1>KidGuard</h1></div><div class="kg-actions">'+button('home','Profiles')+button('family','Family kid-safe library')+button('settings','Settings')+'</div></div><div id="kg-message" role="status" aria-live="polite"></div>'+content+'</div>';
        }
        function message(text) { var box=root.querySelector('#kg-message'); if(box) { box.textContent=text; box.className='kg-notice'; } }
        function setBusy(value) { busy=value; root.setAttribute("aria-busy",String(value)); root.querySelectorAll("button").forEach(function(b){b.disabled=value;}); }
        function fail(e) { message('Could not complete the action. '+(e && e.responseText || e && e.message || 'Reload the page and check the server log.')); }
        async function home() {
            mode='home'; dashboard=await api('Dashboard');
            shell('<p class="kg-muted">Decide what you’re comfortable letting each child watch. Recommendations stay in draft until you approve them.</p>'+
                (dashboard.RecoveryRequired?'<p class="kg-notice kg-danger">An apply was interrupted. The affected account is disabled. Open its library and use Undo / Recover.</p>':'')+
                '<div class="kg-actions">'+button('new','Create child profile',true)+button('scan','Analyze library')+'</div>'+progressHtml()+'<div class="kg-grid">'+dashboard.Profiles.map(function(p){return '<article class="kg-card"><h2>'+esc(p.Label)+'</h2><p class="kg-muted">Age '+p.Age+' · '+esc(p.Approach)+' · '+(p.Applied?'Active':'Draft')+'</p><div class="kg-grid"><div><span class="kg-stat">'+p.Allowed+'</span><br>approved videos</div><div><span class="kg-stat">'+p.Review+'</span><br>need review</div></div><p>'+p.Blocked+' recommended blocked · '+p.Overrides+' overrides</p><button class="emby-button raised button-submit" data-profile="'+p.Id+'">Manage library</button></article>';}).join('')+'</div><h2 style="margin-top:30px">Recent changes</h2>'+auditHtml());
        }
        function progressHtml(){var p=dashboard.Progress;return '<div id="kg-progress">'+(p.Running?'<p>Analyzing '+p.Complete+' / '+p.Total+'</p><progress class="kg-progress" value="'+p.Complete+'" max="'+(p.Total||1)+'"></progress>'+button('cancel','Cancel analysis'):p.Error?'<p>'+esc(p.Error)+'</p>':'<p class="kg-muted">'+dashboard.Total+' movies, series, seasons and episodes analyzed</p>')+'</div>';}
        function auditHtml(){return '<div class="kg-card">'+(dashboard.Audit.length?dashboard.Audit.slice(0,12).map(function(a){return '<p><small>'+esc(new Date(a.At).toLocaleString())+'</small><br>'+esc(a.Action)+' <small>+'+a.Added+' / −'+a.Removed+'</small></p>';}).join(''):'No changes yet.')+'</div>';}
        async function edit(isNew) {
            mode='edit'; var users=await api('Users');
            if(isNew) profile={Id:crypto.randomUUID(),Label:'',Age:8,MaturityOffset:0,Approach:'Conservative',NewMedia:'Review',Tolerances:{},Calibration:[],Revision:0,AllowRemoteAccess:true,AllowTranscoding:true};
            shell('<h2>'+(isNew?'Set up a child profile':'Adjust '+esc(profile.Label))+'</h2><p class="kg-muted">1. Choose the account and comfort level · 2. Calibrate · 3. Review · 4. Approve</p><form id="kg-profile-form"><div class="kg-grid"><section class="kg-card">'+field('Label','Profile label (stored only on this server)',profile.Label,'text','required maxlength="80"')+select('UserId','Jellyfin account',[['','Create a new user on approval']].concat(users.filter(function(u){return !u.IsAdministrator;}).map(function(u){return [u.Id,u.Name];})),profile.UserId||'')+field('NewUsername','New username (if creating)',profile.NewUsername||'')+field('Age','Age',profile.Age,'number','min="0" max="17" required')+'</section><section class="kg-card">'+select('Approach','Recommendation approach',[['Conservative','Conservative'],['Standard','Standard'],['Permissive','Permissive']],profile.Approach)+select('MaturityOffset','Overall maturity',[['-2','Gentler'],['0','Age starting point'],['2','More mature']],String(profile.MaturityOffset))+select('NewMedia','New media behavior',[['Review','Ask me to review (default)'],['Block','Block until manually approved'],['Automatic','Automatically add high-confidence new videos']],profile.NewMedia)+'<p class="kg-muted">Automatic approval is opt-in and only applies after initial approval. Unknown new episodes stay excluded.</p></section></div><details class="kg-card"><summary>Advanced content tolerances</summary><p>Choose a limit only if it matters to you. Missing evidence for a selected dimension produces Review.</p><div class="kg-grid">'+dimensions.map(function(d){return select('dim-'+d,d.replace(/([a-z])([A-Z])/g,'$1 $2'),[['','Use overall setting'],['0','None'],['1','Very low'],['2','Moderate'],['3','High'],['4','No dimension limit']],profile.Tolerances[d] === undefined?'':String(profile.Tolerances[d]));}).join('')+'</div></details><details class="kg-card"><summary>Account permissions</summary>'+checked('AllowRemoteAccess','Allow remote access',profile.AllowRemoteAccess)+checked('AllowDownloads','Allow downloads (downloaded copies cannot later be revoked)',profile.AllowDownloads)+checked('AllowTranscoding','Allow transcoding for client compatibility',profile.AllowTranscoding)+'<p>On approval: administrator, deletion, metadata management, Live TV, external channels, remote control, public sharing and SyncPlay are disabled. Playback/remuxing remains available. Existing folder limits are retained. Native parental tag/rating filters are replaced by this profile’s approved catalog.</p>'+field('EnabledFolders','Optional library folder IDs (comma separated; blank preserves existing limits)',(profile.EnabledFolders||[]).join(','))+'</details><div class="kg-actions"><button type="submit" class="emby-button raised button-submit">Save draft & calibrate</button>'+button('copy','Copy comfort settings from another profile')+'</div></form>');
        }
        async function saveForm() {
            var form=root.querySelector('#kg-profile-form'), data=new FormData(form);
            ['Label','NewUsername','Approach','NewMedia'].forEach(function(k){profile[k]=data.get(k);});
            profile.UserId=data.get('UserId')||null; profile.Age=Number(data.get('Age'));profile.MaturityOffset=Number(data.get('MaturityOffset'));
            profile.Tolerances={};dimensions.forEach(function(d){if(data.get('dim-'+d)!=='')profile.Tolerances[d]=Number(data.get('dim-'+d));});
            ['AllowDownloads','AllowRemoteAccess','AllowTranscoding'].forEach(function(k){profile[k]=data.has(k);});
            profile.EnabledFolders=data.get('EnabledFolders').trim()?data.get('EnabledFolders').split(',').map(function(x){return x.trim();}):null;
            profile=await api('Profiles',profile); await calibrate();
        }
        async function calibrate() {
            mode='calibrate'; var examples=await api('Calibration');
            shell('<h2>What would you allow '+esc(profile.Label)+' to watch?</h2><p>Local titles span the ratings available in your library. Any cards marked “Reference” are hypothetical scenarios, not titles in your library. Yes/No adjusts the comfort ceiling by at most three years. Answers do not grant access; use Always Allow for a lasting title decision.</p>'+(examples.length<6?'<p class="kg-notice">Your library has fewer than six rated examples. You can skip calibration or analyze a larger library. KidGuard will not invent missing title advisories.</p>':'')+'<form id="kg-calibration"><div class="kg-grid">'+examples.map(function(item){var answer=profile.Calibration.find(function(a){return a.ItemId===item.Id;});return '<div class="kg-card"><h3>'+esc(item.Title)+'</h3><p>'+esc(item.Rating)+' · '+esc(item.Kind)+'</p>'+select('cal-'+item.Id,'Would you allow this?',[['Review','Unsure'],['Allow','Yes'],['Block','No']],answer?answer.Answer:'Review')+'</div>';}).join('')+'</div><div class="kg-actions"><button type="submit" class="emby-button raised button-submit">Save calibration & review library</button>'+button('library','Skip to library')+'</div></form>');
        }
        function libraryShell() {
            mode='library';selected.clear();
            shell('<div class="kg-bar"><div><h2>'+esc(profile.Label)+'’s library</h2><p class="kg-muted">Age '+profile.Age+' · '+esc(profile.Approach)+' · Changes remain draft until approval.</p></div><div class="kg-actions">'+button('edit','Adjust maturity')+button('calibrate','Calibrate')+button('scan','Reanalyze')+'</div></div><div class="kg-notice">Allow on a series or season approves its current descendants. A more specific episode decision wins. Future episodes require separate approval. Existing library folder restrictions still apply.</div><form id="kg-filters"><div class="kg-grid">'+field('search','Search titles','','search')+select('status','Recommendation',[['','All statuses'],['Allow','Allowed'],['Block','Blocked'],['Review','Needs review']],'')+select('kind','Media type',[['','Movies and series'],['Movie','Movies'],['Series','Series'],['Season','Seasons'],['Episode','Episodes']],'')+select('sort','Sort',[['title','Title'],['status','Status'],['confidence','Lowest confidence'],['age','Age starting point']],'title')+'</div><details><summary>More filters</summary><div class="kg-grid">'+field('rating','Exact rating','')+field('ageMin','Minimum age starting point','','number')+field('ageMax','Maximum age starting point','','number')+'</div>'+checked('unrated','Unrated or unrecognized',false)+checked('lowConfidence','Low confidence',false)+checked('manual','Manual overrides',false)+'</details><button class="emby-button raised" type="submit">Filter</button></form><div class="kg-actions">'+button('Allow','Allow')+button('Block','Block')+button('AlwaysAllow','Always Allow')+button('AlwaysBlock','Always Block')+button('None','Reset to recommendation')+button('share','Reuse decision for another child')+'</div><p id="kg-count"></p><div id="kg-table" class="kg-table"></div><div class="kg-actions">'+button('prev','Previous')+button('next','Next')+'</div><div class="kg-card"><div id="kg-summary"></div>'+(!profile.UserId?field('newPassword','Password for the new Jellyfin user','','password','minlength="8" autocomplete="new-password"'):'')+'<div class="kg-actions">'+button('apply','APPROVE & APPLY CHILD PROFILE',true)+button('undo','Undo last apply / Recover')+'</div><p class="kg-muted">Only the proposed allowlist is applied. Container choices include current descendants except explicit exceptions. Ordinary Allow/Block choices last until the next analysis; Always choices persist.</p></div>');
        }
        async function library() { if(!profile)return home(); profile=await api('Profiles/'+profile.Id);page=0;libraryShell();await loadRows(); }
        async function loadRows(parent) {
            var form=root.querySelector('#kg-filters'), q=new URLSearchParams(new FormData(form));
            if(!q.get('kind'))q.set('kind','titles');if(parent){q.set('parent',parent);q.set('kind','Episode');}
            ['ageMin','ageMax'].forEach(function(k){if(!q.get(k))q.delete(k);});
            ['unrated','lowConfidence','manual'].forEach(function(k){if(q.has(k))q.set(k,'true');});
            q.set('start',page*100);q.set('limit',100);
            var result=await api('Profiles/'+profile.Id+'/Library?'+q.toString());rows=result.Items;profile.Revision=result.Revision;
            
            root.querySelector('#kg-count').textContent=result.Total+' matching items · page '+(page+1)+' · '+selected.size+' selected';
            root.querySelector('#kg-table').innerHTML='<table><thead><tr><th><input type="checkbox" aria-label="Select this page" id="kg-all"></th><th>Title</th><th>Recommendation</th><th>Confidence*</th><th>Decision</th><th>Access</th></tr></thead><tbody>'+rows.map(function(r){var rec=r.Recommendation||{Decision:'Review',Confidence:0};return '<tr><td><input type="checkbox" aria-label="Select '+esc(r.Item.Title)+'" data-item="'+r.Item.Id+'" '+(selected.has(r.Item.Id)?'checked':'')+'></td><td><button class="kg-link" data-details="'+r.Item.Id+'">'+esc(r.Item.Title)+'</button><br><small>'+esc(r.Item.Kind)+' · '+esc(r.Item.Rating||'Unrated')+'</small></td><td class="kg-status '+rec.Decision+'">'+esc(rec.Decision)+'</td><td>'+rec.Confidence+'%</td><td>'+esc(r.Override==='None'?'Recommendation':r.Override)+'</td><td>'+ (r.Applied?(r.Item.Kind==='Series'||r.Item.Kind==='Season'?'Some episodes approved':'Approved'):r.Proposed?'Draft allow':'Excluded')+'</td></tr>';}).join('')+'</tbody></table><p class="kg-muted"><small>*Confidence is an explainable heuristic, not a measured probability of suitability. Missing dimensions remain unknown.</small></p>';
            root.querySelector('#kg-summary').innerHTML='<h3>Review before applying</h3><p>'+result.ProposedPlayable+' videos in proposed allowlist · '+result.AppliedPlayable+' currently approved</p>';
        }
        async function batch(choice, target) {
            if(!selected.size)return message('Select one or more titles first.');
            var p=target?await api('Profiles/'+target):profile;
            await api('Profiles/'+p.Id+'/Overrides',{Items:Array.from(selected),Choice:choice,Revision:p.Revision});
            if(!target){selected.clear();await loadRows();}message('Draft decisions saved. Review and approve to change access.');
        }
        function details(id) {
            var r=rows.find(function(x){return x.Item.Id===id;});if(!r)return;
            var rec=r.Recommendation;mode='details';
            shell('<h2>'+esc(r.Item.Title)+'</h2><p class="kg-status '+rec.Decision+'">'+esc(rec.Decision)+' · '+rec.Confidence+'% heuristic confidence</p><ul>'+rec.Reasons.map(function(x){return '<li>'+esc(x)+'</li>';}).join('')+'</ul><h3>Sources and evidence</h3>'+r.Evidence.map(function(e){return '<article class="kg-card"><strong>'+esc(e.Source)+'</strong><p>'+esc(e.Note)+'</p><p>Rating: '+esc(e.Rating||'Unknown')+'</p>'+dimensions.map(function(d){return '<span class="kg-inline"><small>'+esc(d)+': '+esc(e.Dimensions[d]===undefined?'unknown':e.Dimensions[d]+'/4')+'</small></span> ';}).join('')+'</article>';}).join('')+'<p>Parent override: '+esc(r.Override)+'</p><div class="kg-actions">'+button('detailAllow','Always Allow')+button('detailBlock','Always Block')+button('refresh','Refresh this metadata')+(r.Item.Kind==='Series'||r.Item.Kind==='Season'?button('episodes','Inspect current episodes'):'')+button('library','Back to library')+'</div>');
            selected=new Set([id]);
        }
        async function settings() {
            mode='settings';dashboard=await api('Dashboard');var s=dashboard.Settings;
            shell('<h2>Provider & family settings</h2><form id="kg-settings" class="kg-card">'+checked('ExternalEnabled','Enable optional TMDb certification lookup',s.ExternalEnabled)+field('token','TMDb API Read Access Token (blank keeps existing token)', '', 'password','autocomplete="off"')+'<p>'+ (dashboard.HasTmdbToken?'A token is configured.':'No token configured.')+'</p>'+checked('clearToken','Remove stored token',false)+select('Country','Certification country',[['US','United States'],['GB','United Kingdom'],['DE','Germany']],s.Country)+field('CacheDays','Cache lifetime (days)',s.CacheDays,'number','min="1" max="365"')+field('AutoConfidence','Automatic approval minimum confidence',s.AutoConfidence,'number','min="90" max="100"')+checked('FamilyRequiresAll','Family catalog requires approval for every active child',s.FamilyRequiresAll)+'<p class="kg-notice">TMDb receives only a media provider ID and the network request’s source IP. No child label, age, username or viewing history is sent. Certifications do not provide detailed scene advisories. This product uses the TMDB API but is not endorsed or certified by TMDB.</p><p>Local advisory metadata uses tags such as <code>Advisory:Fear:2</code> (0–4). Tags are visible in media metadata; do not include private child information.</p><button class="emby-button raised button-submit" type="submit">Save settings</button></form>');
        }
        async function family() {
            mode='family';var items=await api('Family');
            shell('<h2>Family kid-safe library</h2><p>The KidSafe catalog combines approved child libraries. Family catalog changes do not grant a child access. Search, then include or exclude specific items.</p>'+field('familySearch','Search catalog','','search')+'<div id="kg-family" class="kg-table"></div>');
            function render(){var query=root.querySelector('[name=familySearch]').value.toLowerCase();var shown=items.filter(function(x){return x.Title.toLowerCase().includes(query);}).slice(0,250);root.querySelector('#kg-family').innerHTML='<table><tr><th>Title</th><th>KidSafe</th><th>Manual catalog choice</th></tr>'+shown.map(function(i){return '<tr><td>'+esc(i.Title)+' <small>'+i.Kind+'</small></td><td>'+(i.Allowed?'Included':'Excluded')+'</td><td><button class="emby-button" data-family="'+i.Id+'" data-value="'+(!i.Allowed)+'">'+(i.Allowed?'Exclude':'Include')+'</button> <button class="emby-button" data-family="'+i.Id+'" data-value="reset">Reset</button></td></tr>';}).join('')+'</table><p>Showing up to 250 matches. Narrow the search for large libraries.</p>';}
            root.querySelector('[name=familySearch]').addEventListener('input',render);render();
        }
        root.addEventListener('submit',function(e){e.preventDefault();if(busy)return;setBusy(true);(async function(){
            if(e.target.id==='kg-profile-form')return saveForm();
            if(e.target.id==='kg-filters'){page=0;return loadRows();}
            if(e.target.id==='kg-calibration'){profile.Calibration=Array.from(new FormData(e.target)).map(function(pair){return {ItemId:pair[0].slice(4),Answer:pair[1]};});profile=await api('Profiles',profile);return library();}
            if(e.target.id==='kg-settings'){var d=new FormData(e.target),s=dashboard.Settings;s.ExternalEnabled=d.has('ExternalEnabled');s.TmdbToken=d.get('token');s.Country=d.get('Country');s.CacheDays=Number(d.get('CacheDays'));s.AutoConfidence=Number(d.get('AutoConfidence'));s.FamilyRequiresAll=d.has('FamilyRequiresAll');if(d.has('clearToken'))s.TmdbToken='';await api('Settings',{Settings:s,ReplaceToken:!!s.TmdbToken||d.has('clearToken')});message('Settings saved. Reanalyze to use updated provider settings.');}
        })().catch(fail).finally(function(){setBusy(false);});});
        root.addEventListener('change',function(e){if(e.target.dataset.item){if(e.target.checked)selected.add(e.target.dataset.item);else selected.delete(e.target.dataset.item);}if(e.target.id==='kg-all'){root.querySelectorAll('[data-item]').forEach(function(box){box.checked=e.target.checked;if(box.checked)selected.add(box.dataset.item);else selected.delete(box.dataset.item);});}});
        root.addEventListener('click',function(e){var el=e.target.closest('button');if(!el||!el.dataset.act&&!el.dataset.profile&&!el.dataset.details&&!el.dataset.family)return;if(busy)return;setBusy(true);(async function(){
            if(el.dataset.profile){profile=await api('Profiles/'+el.dataset.profile);return library();}
            if(el.dataset.details)return details(el.dataset.details);
            if(el.dataset.family){await api('Family',{Items:[el.dataset.family],Allowed:el.dataset.value==='reset'?null:el.dataset.value==='true'});return family();}
            var act=el.dataset.act;
            if(act==='home')return home();if(act==='new')return edit(true);if(act==='edit')return edit(false);if(act==='library')return library();if(act==='calibrate')return calibrate();if(act==='settings')return settings();if(act==='family')return family();
            if(act==='scan'){await api('Analyze',{});message('Analysis started in the background. Open Profiles for progress; reload the library when it finishes.');return;}
            if(act==='cancel'){await api('Analyze/Cancel',{});return home();}
            if(['Allow','Block','AlwaysAllow','AlwaysBlock','None'].includes(act))return batch(act);
            if(act==='prev'){page=Math.max(0,page-1);return loadRows();}if(act==='next'){page++;return loadRows();}
            if(act==='detailAllow'||act==='detailBlock'){await batch(act==='detailAllow'?'AlwaysAllow':'AlwaysBlock',profile.Id);return library();}
            if(act==='refresh'){await api('Analyze?refresh='+Array.from(selected)[0],{});message('Metadata refresh started.');return;}
            if(act==='episodes'){var id=Array.from(selected)[0];libraryShell();return loadRows(id);}
            if(act==='apply'){
                if(!confirm('Apply the reviewed allowlist and displayed child-account permissions now? Only the proposed allowlist, including the current descendants of your container choices, will be applied.'))return;
                var pw=root.querySelector('[name=newPassword]');await api('Profiles/'+profile.Id+'/Apply',{Revision:profile.Revision,Confirm:true,NewPassword:pw?pw.value:null});if(pw)pw.value='';await library();message('Approved library applied.');return;
            }
            if(act==='undo'){if(!confirm('Restore the policy before the last apply? Undoing initial setup restores the user’s ORIGINAL access, which may be unrestricted.'))return;await api('Profiles/'+profile.Id+'/Undo',{Confirm:true});await library();message('Previous policy restored.');return;}
            if(act==='copy'||act==='share'){
                dashboard=await api('Dashboard');var other=dashboard.Profiles.filter(function(p){return p.Id!==profile.Id;});if(!other.length)return message('Create another profile first.');
                var label=prompt('Enter a profile label: '+other.map(function(p){return p.Label;}).join(', '));var found=other.find(function(p){return p.Label===label;});if(!found)return;
                if(act==='copy'){var source=await api('Profiles/'+found.Id);['MaturityOffset','Approach','Tolerances'].forEach(function(k){profile[k]=source[k];});return edit(false);}
                var choice=prompt('Decision to copy to '+found.Label+': AlwaysAllow or AlwaysBlock','AlwaysBlock');if(!['AlwaysAllow','AlwaysBlock'].includes(choice))return;return batch(choice,found.Id);
            }
        })().catch(fail).finally(function(){setBusy(false);});});
        view.addEventListener('viewshow',function(){home().catch(fail);clearInterval(poll);poll=setInterval(function(){if(mode==='home'&&!busy&&dashboard&&dashboard.Progress.Running){setBusy(true);home().catch(fail).finally(function(){setBusy(false);});}},5000);});
        view.addEventListener('viewhide',function(){clearInterval(poll);});
}
